In [2]:
import numpy as np

In [4]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = a.mean (axis = 0)

In [7]:
mean_a

array([2. , 8.4])

In [8]:
a_centered = a - mean_a

In [9]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [36]:
c = a_centered[ : 5, :1]

In [37]:
ct = c.T

In [38]:
ct

array([[-1.,  0.,  1.,  1., -1.]])

In [24]:
d = a_centered[ :5, 1:]

In [39]:
a_centered_sp = np.dot(ct,d)

In [43]:
a_centered_sp

array([[8.]])

In [45]:
k = a_centered_sp / 4

In [46]:
k

array([[2.]])